#!/usr/bin/env bash
# This script displays the content of the file /et/passwd but only displays:
# username
# user id
# Home directory path for the user

filename='/etc/passwd'

while read line
do
  echo "$line" | cut -d ":" -f 1,3,6
done < $filename
