#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using while and IFS
# Format:
# The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO

filename='/etc/passwd'


while IFS=":" read -a data
do
  echo "The user ${data[0]} is part of the ${data[3]} gang, lives in ${data[5]} and rides ${data[6]}. ${data[2]}'s place is protected by the passcode ${data[1]}, more info about the user here: ${data[4]}"
done < $filename
